#!/bin/bash
INTERFACE_REPOSITORY="splashscreen_interface"
BRANCH="dora"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR/../../
ROOT_DIRECTORY=`pwd`
ARCHITECH_MANIFESTS_REPOSITORY="architech-manifest"
ARCHITECH_MANIFEST="${ROOT_DIRECTORY}/${ARCHITECH_MANIFESTS_REPOSITORY}/architech"
PARTNERS_MANIFEST="${ROOT_DIRECTORY}/${ARCHITECH_MANIFESTS_REPOSITORY}/partners"
ARCHITECH_DIRECTORY="architech"
PARTNERS_DIRECTORY="partners"
BOARDS_MANIFEST="boards_manifest"
BOARDS_MANIFEST_DIRECTORY="boards_manifest"
SPLASHSCREEN_DIRECTORY="splashscreen"

function internet_error {
    echo "ERROR: Impossible to connect to internet, double check your Internet connection"
    exit 1   
}

function board_installation_error {
    echo "ERROR: Impossible to install/update $1 board"
}

if [ ! -d ${INTERFACE_REPOSITORY} ]
then
    echo "Cloning https://github.com/architech-boards/${INTERFACE_REPOSITORY}.git (branch $BRANCH)..."
    git clone -b ${BRANCH} https://github.com/architech-boards/${INTERFACE_REPOSITORY}.git > /dev/null 2>&1
    [ $? -eq 0 ] || internet_error
else
    cd ${INTERFACE_REPOSITORY}
    echo "Updating repository ${INTERFACE_REPOSITORY}, this might take several minutes..."
    git pull > /dev/null 2>&1
    [ $? -eq 0 ] || internet_error
fi

cd ${ROOT_DIRECTORY}
if [ ! -d ${ARCHITECH_MANIFESTS_REPOSITORY} ]
then
    echo "Cloning https://github.com/architech-boards/architech-manifest.git (branch $BRANCH)..."
    git clone -b ${BRANCH} https://github.com/architech-boards/architech-manifest.git > /dev/null 2>&1
    [ $? -eq 0 ] || internet_error
else
    cd ${ARCHITECH_MANIFESTS_REPOSITORY}
    echo "Updating repository ${ARCHITECH_MANIFESTS_REPOSITORY}..."
    git pull > /dev/null 2>&1
    [ $? -eq 0 ] || internet_error
fi

while read ARCHITECH_BOARD
do
    BOARD_ALIAS=`echo ${ARCHITECH_BOARD} | awk -F"|" '{print $1}'`
    BOARD_REPOSITORY=`echo ${ARCHITECH_BOARD} | awk -F"|" '{print $2}'`
    BOARD_BRANCH=`echo ${ARCHITECH_BOARD} | awk -F"|" '{print $3}'`
    mkdir -p ${ROOT_DIRECTORY}/${ARCHITECH_DIRECTORY}/${BOARD_ALIAS}
    cd ${ROOT_DIRECTORY}/${ARCHITECH_DIRECTORY}/${BOARD_ALIAS}
    if [ ! -e "${SPLASHSCREEN_DIRECTORY}" ]
    then
        echo "Cloning ${BOARD_REPOSITORY} (branch ${BOARD_BRANCH}), this might take several minutes..."
        git clone -b ${BOARD_BRANCH} ${BOARD_REPOSITORY} ${SPLASHSCREEN_DIRECTORY} > /dev/null 2>&1
        [ $? -eq 0 ] || internet_error        
        cd ${SPLASHSCREEN_DIRECTORY}
    else
        echo "Updating ${BOARD_ALIAS} from ${BOARD_REPOSITORY}, this might take several minutes..."
        cd ${SPLASHSCREEN_DIRECTORY}
        git pull > /dev/null 2>&1
        [ $? -eq 0 ] || internet_error
    fi
    echo "Installing ${BOARD_ALIAS}, this might take several minutes..."
    ./run_install
    [ $? -eq 0 ] || board_installation_error ${BOARD_ALIAS}
done < "${ARCHITECH_MANIFEST}"

while read ARCHITECH_PARTNER
do
    PARTNER_ALIAS=`echo ${ARCHITECH_PARTNER} | awk -F"|" '{print $1}'`
    PARTNER_REPOSITORY=`echo ${ARCHITECH_PARTNER} | awk -F"|" '{print $2}'`
    PARTNER_BRANCH=`echo ${ARCHITECH_PARTNER} | awk -F"|" '{print $3}'`
    mkdir -p ${ROOT_DIRECTORY}/${PARTNERS_DIRECTORY}/${PARTNER_ALIAS}
    cd ${ROOT_DIRECTORY}/${PARTNERS_DIRECTORY}/${PARTNER_ALIAS}
    if [ ! -e ${BOARDS_MANIFEST_DIRECTORY} ]
    then
        echo "Cloning ${PARTNER_REPOSITORY} (branch ${PARTNER_BRANCH}), this might take several minutes..."
        git clone -b ${PARTNER_BRANCH} ${PARTNER_REPOSITORY} ${BOARDS_MANIFEST_DIRECTORY} > /dev/null 2>&1
        [ $? -eq 0 ] || internet_error
    else
        echo "Updating ${PARTNER_ALIAS} from ${PARTNER_REPOSITORY}, this might take several minutes..."
        cd ${BOARDS_MANIFEST_DIRECTORY}
        git pull > /dev/null 2>&1
        [ $? -eq 0 ] || internet_error
    fi
    PARTNER_BOARDS_MANIFEST="${ROOT_DIRECTORY}/${PARTNERS_DIRECTORY}/${PARTNER_ALIAS}/${BOARDS_MANIFEST_DIRECTORY}/${BOARDS_MANIFEST}"

    while read PARTNER_BOARD
    do
        BOARD_ALIAS=`echo ${PARTNER_BOARD} | awk -F"|" '{print $1}'`
        BOARD_REPOSITORY=`echo ${PARTNER_BOARD} | awk -F"|" '{print $2}'`
        BOARD_BRANCH=`echo ${PARTNER_BOARD} | awk -F"|" '{print $3}'`
        mkdir -p ${ROOT_DIRECTORY}/${PARTNERS_DIRECTORY}/${PARTNER_ALIAS}/${BOARD_ALIAS}
        cd ${ROOT_DIRECTORY}/${PARTNERS_DIRECTORY}/${PARTNER_ALIAS}/${BOARD_ALIAS}
        if [ ! -e "${SPLASHSCREEN_DIRECTORY}" ]
        then
            echo "Cloning ${BOARD_REPOSITORY} (branch ${BOARD_BRANCH}), this might take several minutes..."
            git clone -b ${BOARD_BRANCH} ${BOARD_REPOSITORY} ${SPLASHSCREEN_DIRECTORY} > /dev/null 2>&1
            [ $? -eq 0 ] || internet_error
            cd ${SPLASHSCREEN_DIRECTORY}
        else
            echo "Updating ${BOARD_ALIAS} from ${BOARD_REPOSITORY}, this might take several minutes..."
            cd ${SPLASHSCREEN_DIRECTORY}
            git pull > /dev/null 2>&1
            [ $? -eq 0 ] || internet_error
        fi
        echo "Installing ${BOARD_ALIAS}, this might take several minutes..."
        ./run_install
        [ $? -eq 0 ] || board_installation_error $BOARD_ALIAS
    done < "${PARTNER_BOARDS_MANIFEST}"

done < "${PARTNERS_MANIFEST}"

exit 0
